services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "6432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10
    env_file:
      - .env

  app:
      build: .
      ports:
        - "8000:8000"
      depends_on:
        - db
      environment:
        DATABASE_URL: postgresql+psycopg://app_user:app_password@db:5432/app_db
      entrypoint: ./entrypoint.sh

volumes:
  pgdata:
